[project]
name = "sc4023-big-data-management"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pandas>=3.0.0",
    "parquet>=1.3.1",
    "pyarrow>=23.0.0",
]
